{{- $namespace := .Release.Namespace -}}
{{- $releaseName := .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-redis-secret
  namespace: {{ $namespace }}
type: Opaque
data:
  REDIS_PASSWORD: {{ index .Values "redis-cluster" "password" | b64enc }}
