{{- if and (eq .Values.loadbalancer.provider "azure") .Values.loadbalancer.http.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-http-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    appgw.ingress.kubernetes.io/use-regex: 'true'
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/request-timeout: "300"
    {{- if .Values.loadbalancer.http.ssl.enabled }}
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{ .Values.loadbalancer.http.ssl.certificateRef }}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tbmq.node.label" . }}
                port:
                  name: http
{{- end }}
