{{- if and .Values.awscontroller.mqtt.mutualTls.enabled (empty .Values.awscontroller.mqtt.mutualTls.existingConfigMap) }}
{{- $namespace := .Release.Namespace -}}
{{- $releaseName := .Release.Name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-tbmq-node-default-mqtts-config" $releaseName }}
  namespace: {{ $namespace }}
  labels:
    name: {{ printf "%s-tbmq-node-default-mqtts-config" $releaseName }}
data:
  server.pem: |-
    {{- .Files.Get .Values.awscontroller.mqtt.mutualTls.serverCertificate | nindent 4 }}
  mqttserver_key.pem: |-
    {{- .Files.Get .Values.awscontroller.mqtt.mutualTls.privateKey | nindent 4 }}
{{- end }}
