{{- $namespace := .Release.Namespace -}}
{{- $releaseName := .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-postgres-secret
  namespace: {{ $namespace }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  {{- else }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.externalPostgresql.password | b64enc }}
  {{- end }}
